In [1]:
import numpy as np
import pandas as pd

In [2]:
name_columns = np.load("/Users/gblasd/Documents/Code/SmartBnB/airflow/models/text_embeddings_columns.npy", allow_pickle=True).tolist()

In [4]:
len(name_columns)

466

In [5]:
data = pd.DataFrame(np.load("/Users/gblasd/Documents/Code/SmartBnB/airflow/models/text_embeddings.npy", allow_pickle=True), columns=name_columns)

In [17]:
text_embeddings_df = np.load("/Users/gblasd/Documents/Code/SmartBnB/airflow/models/text_embeddings_df.npy", allow_pickle=True)
text_embeddings_df = [ str(x) for x in text_embeddings_df]

In [18]:
print(text_embeddings_df)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '176', '177', '178', '179', '180', '181', '182', '183', '184', '185', '186', '187', '188', '189', '190', '191', '192', '193', '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '204', '205', '206', '207', '208', '209', '210', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220', '221', '222', '223', '224', '225', '226', '227', '228', '229', '230', '231', '232', '233', '234', '235', '236', '237', '238', '239', '240', '241', '242', '243', '244', '245', '246', '247', '248', '249', '250', '251', '252', '253', '254', '255', '256', '257', '258', '259', '260', '261', '262', '263', '264', '265', '266', '267', '268', '269', '270', '271', '272', '273', '274', '275', '276', '277', '278', '279', '280', '281', '282', '283', '284', '285', '286', '287', '288', '289', '290', '291', '292', '293', '294', '295', '296', '297', '298', '299', '300', '301', '302', '303', '304', '305', '306', '307', '308', '309', '310', '311', '312', '313', '314', '315', '316', '317', '318', '319', '320', '321', '322', '323', '324', '325', '326', '327', '328', '329', '330', '331', '332', '333', '334', '335', '336', '337', '338', '339', '340', '341', '342', '343', '344', '345', '346', '347', '348', '349', '350', '351', '352', '353', '354', '355', '356', '357', '358', '359', '360', '361', '362', '363', '364', '365', '366', '367', '368', '369', '370', '371', '372', '373', '374', '375', '376', '377', '378', '379', '380', '381', '382', '383']

In [19]:
type(text_embeddings_df)

list

In [20]:
data[text_embeddings_df]

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.390157,0.024232,0.052374,0.166661,0.159259,-0.045698,0.103171,-0.099799,0.205302,0.297624,...,0.085061,0.041458,0.172836,0.125905,0.171682,0.007319,-0.079437,0.228391,-0.295289,-0.087758
1,0.220665,0.124108,-0.317978,0.154623,0.145837,0.017048,-0.050218,-0.203268,0.047957,0.147089,...,-0.016839,-0.193337,-0.160876,-0.097394,0.052607,0.062775,0.215242,0.297243,-0.237348,0.279084
2,0.434512,0.190217,0.108461,-0.021005,-0.062991,0.088235,-0.178869,0.160342,0.053652,-0.065016,...,-0.095976,0.184586,-0.197258,0.090775,0.044858,-0.049864,0.017258,-0.066355,-0.177256,-0.004435
3,0.022042,-0.083446,0.0836,0.132329,0.178235,0.147434,-0.290863,-0.170941,-0.121592,0.294593,...,-0.255525,-0.147788,-0.108989,0.160024,-0.098826,0.013474,-0.171905,0.012057,-0.104866,-0.071651
4,0.269904,-0.035236,0.131066,0.267587,-0.075197,0.064578,-0.1636,-0.049359,-0.136958,0.153538,...,0.043939,0.073353,-0.036856,-0.18986,0.013089,0.138275,-0.046709,-0.118745,-0.147358,-0.156382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26396,0.415379,0.053998,0.097606,0.172756,0.117692,0.08772,-0.027149,0.143152,0.260529,0.240371,...,-0.089498,-0.081301,-0.146743,0.175181,-0.06962,0.129872,-0.120311,-0.232026,-0.60366,-0.144313
26397,0.309337,0.223371,-0.100936,-0.054369,0.321954,0.168014,-0.090324,0.135816,-0.03901,0.043961,...,0.186258,0.103574,-0.020825,-0.011262,-0.125659,-0.044992,-0.079739,-0.224561,-0.195112,0.044794
26398,0.268647,0.042311,0.163823,0.051249,0.115693,-0.080581,-0.22636,0.13139,-0.152705,0.149799,...,0.086537,-0.002821,-0.386278,0.185652,-0.03217,-0.164456,0.0109,0.187553,-0.265553,-0.004502
26399,0.512666,0.128742,-0.007049,0.113771,0.010666,0.069646,-0.178206,-0.040284,0.031425,0.081178,...,0.166714,0.283139,-0.055618,-0.101846,0.120392,0.093835,0.214505,-0.043242,-0.196446,-0.068025
26400,0.388629,0.016991,-0.118153,0.03685,0.11595,0.187818,-0.305755,-0.146532,-0.043407,0.307346,...,0.112896,0.249609,-0.049691,0.072611,-0.12213,-0.023744,0.171994,0.095574,-0.105874,0.162961

In [2]:
import sqlite3
import pandas as pd
import numpy as np

In [10]:
text_embeddings = np.load('/Users/gblasd/Documents/SmartBnB/db/text_embeddings.npy', allow_pickle=True  )

In [15]:
text_embeddings_df = pd.DataFrame(text_embeddings)

In [21]:
text_embeddings_df.select_dtypes(exclude=['object'])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[26401 rows x 0 columns]